@startuml

TestCase -> Bicicleta ** : establecerPrecioPorDia(precioPorDia Double)
return unaBici
TestCase -> AlquilerDiario ** : rentar(unaBici)
return unAlquilerDiario
TestCase -> Client: agregar(AlquilerDiario)

TestCase -> Client: saldoAdeudado()
Client -> AlquilerDiario: deuda()

AlquilerDiario -> Bici ** : porDia
return unaBiciPorDia

AlquilerDiario -> AlquilerPeriodo ** : rentarPor(unaBiciPorDia, 1)

AlquilerPeriodo -> Bicicleta: deuda()
return precioPorDia * 1

@enduml 
