@startuml

title: Un cliente alquila una bicicleta durante un día

TestCase -> Bicicleta ** : establecerPrecioPorDia(precioPorDia Double)
return unaBici
TestCase -> AlquilerDiario ** : rentar(unaBici)
return unAlquilerDiario
TestCase -> Client: agregar(AlquilerDiario)

TestCase -> Client: saldoAdeudado()
Client -> AlquilerDiario: deuda()

AlquilerDiario -> Bici ** : porDia
return unaBiciPorDia

AlquilerDiario -> AlquilerPeriodo ** : rentarPor(unaBiciPorDia, 1)

AlquilerPeriodo -> AlquilerPeriodo: deuda()
AlquilerPeriodo --> AlquilerDiario: precioPorDia * 1
AlquilerDiario --> Client: precioPorDia * 1
Client --> TestCase: precioPorDia * 1

@enduml 
