@startuml

TestCase -> Bicicleta ** : con(precioPorDia, precioDiario Double)
return unaBici
TestCase -> AlquilerPeriodo ** : rentar(unaBici)

TestCase -> Client: agregar(AlquilerPorDiasDiario)

TestCase -> Client: saldoAdeudado()
return precioPorDia * dias

Client -> AlquilerPeriodo: deudaPor(numeroDias)
return precioPorDia * dias


AlquilerPeriodo -> Bicicleta: deudaPor(dias)
return precioPorDia * dias



@enduml 
