@startuml

title: Un cliente alquila una bicicleta durante 5 unidades de tiempo.  \nEl precio por unidad de tiempo es 3 $/u \n (la unidad de tiempo puede ser días).

TestCase -> Bici ** : establecerPrecio(precioPorPeriodo Double)
return unaBici
TestCase -> AlquilerPeriodo ** : rentarPor(unaBici, 5)

TestCase -> Client: agregar(AlquilerPorDiasDiario)

TestCase -> Client: saldoAdeudado()

Client -> AlquilerPeriodo: deuda()

AlquilerPeriodo -> Bici: deudaPorPeriodo(5)
return precioPorPeriodo * 5

AlquilerPeriodo --> Client: precioPorPeriodo * 5
Client --> TestCase: precioPorPeriodo * 5



@enduml 
